spring:
  cloud:
    config:
      username: ${config_security_username}
      password: ${config_security_password}
      uri:  ${config_security_url}
  config:
    import: "configserver:"
  application:
    name: post-service